re-addging results for 24 bus

diff --git a/v7/run_tests b/v7/run_tests
--- a/v7/run_tests
+++ b/v7/run_tests
@@ -1,3 +1,17 @@
 #!/bin/bash
-/home/sidhant/license_servers
-srun julia Optimized_linear_for_cluster.jl $1 $2 $3 $4
+for i in $(seq 1 100)
+do
+   /home/sidhant/license_servers
+   if [ $? -eq 0 ]
+   then 
+      echo "successfully obtained license"
+      break
+   else
+      echo "retry $i"
+   fi
+   sleep 3
+done
+echo "failed to connect to server"
+
+
+srun julia Optimized_linear_for_cluster.jl $1 $2 $3 $4 $5
